# Generated by Django 2.2.16 on 2022-07-16 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Название опроса', max_length=200, verbose_name='Название')),
                ('description', models.TextField(help_text='Название опроса', verbose_name='Описание')),
                ('date_created', models.DateTimeField(auto_now_add=True, help_text='Дата создания опроса', verbose_name='Дата')),
                ('reward', models.DecimalField(blank=True, decimal_places=2, help_text='Награда за прохождение опроса', max_digits=6, verbose_name='Награда')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_type', models.CharField(choices=[('OP', 'Открытый вопрос'), ('SA', 'Один ответ'), ('MA', 'Несколько вариантов ответа')], default='SA', help_text='Тип вопроса', max_length=2, verbose_name='Тип')),
                ('text', models.TextField(help_text='Текст вопроса', verbose_name='Текст')),
                ('poll', models.ForeignKey(help_text='Опрос, в котором находится вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='polls.Poll', verbose_name='Опрос')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Текст ответа', verbose_name='Текст')),
                ('poll', models.ForeignKey(help_text='Опрос', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Poll', verbose_name='Опрос')),
                ('question', models.ForeignKey(help_text='Заданный вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='polls.Question', verbose_name='Вопрос')),
            ],
        ),
    ]
