# Generated by Django 2.2.16 on 2022-07-18 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=models.CharField(choices=[('bg-secondary', 'BLACK'), ('bg-primary', 'BLUE'), ('bg-danger', 'RED'), ('bg-success', 'GREEN')], help_text='Цвет', max_length=20, verbose_name='Цвет'),
        ),
        migrations.AlterField(
            model_name='colors',
            name='cost',
            field=models.DecimalField(decimal_places=2, help_text='Цена покупки цвета', max_digits=6, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_color',
            field=models.ForeignKey(blank=True, help_text='Цвет бэкграунда', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_backgrnd_color', to='polls.Colors', verbose_name='Цвет бэкграунда'),
        ),
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Баланс юзера', max_digits=6, verbose_name='Баланс'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_color',
            field=models.ForeignKey(blank=True, help_text='Цвет рамки логина', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_login_color', to='polls.Colors', verbose_name='Цвет логина'),
        ),
    ]
