# Generated by Django 2.2.16 on 2022-07-16 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.ForeignKey(help_text='Ответ пользователя', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='polls.Answer', verbose_name='Ответ')),
                ('poll', models.ForeignKey(help_text='Опрос', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='polls.Poll', verbose_name='Опрос')),
                ('question', models.ForeignKey(help_text='Заданный вопрос', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to='polls.Question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(help_text='Пользователь, давший ответ', on_delete=django.db.models.deletion.CASCADE, related_name='user_answers', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
    ]
