# Generated by Django 2.2.16 on 2022-07-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20220718_2100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='poll',
            name='reward',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, help_text='Награда за прохождение опроса', max_digits=6, verbose_name='Награда'),
        ),
    ]
