# Generated by Django 2.2.16 on 2022-07-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20220718_2234'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='purchase',
            name='unique purchase',
        ),
        migrations.RemoveConstraint(
            model_name='useranswer',
            name='unique poll try',
        ),
        migrations.AddConstraint(
            model_name='purchase',
            constraint=models.UniqueConstraint(fields=('color', 'user', 'type'), name='unique_purchase'),
        ),
        migrations.AddConstraint(
            model_name='useranswer',
            constraint=models.UniqueConstraint(fields=('poll', 'question', 'user'), name='unique_poll_try'),
        ),
    ]
