# Generated by Django 2.2.16 on 2022-07-17 16:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20220717_1716'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colors',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('color', models.CharField(choices=[('BK', 'BLACK'), ('BL', 'BLUE'), ('RED', 'RED'), ('GR', 'GREEN')], default='BK', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='background_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_backgrnd_color', to='users.Colors'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_color',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users_login_color', to='users.Colors'),
        ),
    ]
