# Generated by Django 2.2.16 on 2022-07-17 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20220717_1957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colors',
            name='color',
            field=models.CharField(choices=[('BK', 'BLACK'), ('BL', 'BLUE'), ('RED', 'RED'), ('GR', 'GREEN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='colors',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='user',
            name='background_color',
            field=models.ForeignKey(default='BK', on_delete=django.db.models.deletion.CASCADE, related_name='users_backgrnd_color', to='users.Colors'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_color',
            field=models.ForeignKey(default='BK', on_delete=django.db.models.deletion.CASCADE, related_name='users_login_color', to='users.Colors'),
        ),
    ]
