# Generated by Django 2.2.16 on 2022-07-17 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220717_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='background_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_backgrnd_color', to='users.Colors'),
        ),
        migrations.AlterField(
            model_name='user',
            name='login_color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users_login_color', to='users.Colors'),
        ),
    ]
